### PR TITLE
Hi (my WIP work on a flashrom serprog mode ... NOT FOR MERGE, but as a discussion thread)

### PR DESCRIPTION
**Pull request by urjaman**
So yeah thanks a lot for the work on supoprting the 6261 :) (found by looking through the fernly forks graph),
it actually loads code on my GT08S/GT08 watches here.

The firmware/fernly itself though seems ... broken, somewhat? atleast it didnt talk to me much (/made my terminal go wonky and need a blind "reset" typed).
I guess that could be the same problem i'm having with my serprog-stage1 serial port...

Anyways i thought it was silly to have a patch to add one more serial-port based SPI programmer to flashrom since it already has a generic serial port based SPI capable programmer (serprog) (yeah i'm kinda the main author of that, so i'm biased... doesnt mean i'm not right) and that i could quickly whip up a stage1 thats just a serprog fw.

The SPI seems to work (i get a sane RDID on the debug attempt) but the fw itself seems to stop talking after that initial hello etc. I'll likely continue trying my debugging with this, but decided to show what i've made so far (and to maybe get more eyeballs on this...)

And yeah to be honest my attempt is to get a FOSS way to dump and flash fw to these watches, so i can hack on(/reverse a bit) the stock OS (since that is a simpler and more featureful ambition for now than a full replacement), but i'll document what i find so maybe that'll help someone on the fully-FOSS side too :) (I mean, i guess everyone could use a flashing method, regardless of the binary being flashed.)

### CODE REVIEW

**Comment by craigcomstock** [comment]
Thanks for the code and comments. I scanned through it and didn't take much away from it but I am fairly new to much of this low-level firmware programming. I'll look some more soon.

**Comment by urjaman** [comment]
Yeah i'll close this (you can still integrate what you want later from my tree if you like, but i'm not making "finalized" commits anyways, just hacks) since i'm not expecting anything to be done about this, and actually found some better forums for talking about fernvale stuff if i need to.

**Comment by craigcomstock** [comment]
Let me know what the forum is. I am actively working on osmocom-bb for actual fernvale hardware (and maybe watches like you mentioned) so forums would help.

**Comment by urjaman** [comment]
https://www.kosagi.com/forums/index.php has a section for fernvale 

I didnt yet join or anything, but mostly realized i had somehow misparsed you as the initial source for the 6261 support (i think, whatever).

Btw, i did get the flashrom serprog working using the Boot ROM provided usb serial routines, so thats functional-enough (i might come back to making the fernvale usb serial work better).

Currently I'm trying to figure out the compression used in:
952928        0xE8A60         Mediatek File Info File Type: VIVA Flash Type: Serial Flash No Signature Load Address: 0x100E8A58 File Length: 2770268 Maximum Size: -1 Content Offset: 0x38 Signature Lenght: 0 Jump Offset: 0 POST_BUILD_DONE XIP (Execute In Place)
^ that thing...

**Pull request closed without merging**
